; Listing generated by Microsoft (R) Optimizing Compiler Version 18.00.31101.0 

	TITLE	E:\hxp\books\游戏人工智能编程修订版\Buckland_PGAIBE_Source_VC6-VS2010\VS2010\Buckland_Chapter7 to 10_Raven\goals\Goal_SayPhrase.cpp
	.686P
	.XMM
	include listing.inc
	.model	flat

INCLUDELIB LIBCMTD
INCLUDELIB OLDNAMES

END
